### PR TITLE
VisTrails version for Python 3

### PR DESCRIPTION
**Pull request by rexissimus**

### CODE REVIEW

**Comment by rexissimus** [comment]
First view of GUI running Python 3 and PyQt5:
py3pyqt5

**Comment by remram44** [comment]
[python-future](https://pypi.python.org/pypi/future) is a compatibility layer for Python 2 & 3 compatible code (much like [six](https://pypi.python.org/pypi/six)) that includes a tool to convert Python 2 code to the library ([futurize](http://python-future.org/automatic_conversion.html)). But I'm still very wary of moving towards supporting both versions.

**Comment by tacaswell** [comment]
If you are wary of supporting both consider dropping 2.  Core python is going to drop support in 2020 and upstream packages are going to start dropping python 2 support for new release in the next few years.

From maintaining mpl on a common 2/3 code base I can attest that a great many of the changes we have had to make to support python 3 have been bug fixes of things that were never _quite_ working or were just working by chance in python 2 (a great many issues related to the process-to-process stability of dictionary iteration order).

**Comment by rexissimus** [comment]
Thanks for the feedback! The biggest issue is probably breaking compatibility with existing code. But I think most are now willing to move over.

It looks like we are leaning towards maintaining the python 2 branch as a bugfix branch while possibly backporting some functionality like unicode support.

For the Python 3 branch we are considering some major changes like a new multi-threaded workflow interpreter, and this would probably be of limited use for legacy code anyway.

**Comment by remram44** [comment]
Decision is to develop on #1143 directly.

**Pull request closed without merging**
