### PR TITLE
New persistence package

### PR DESCRIPTION
**Pull request by remram44**
After meeting with Matthias Troyer, we established the need for a new persistence package, that wouldn't be based on Git.

Meeting summary and design directions: http://vistrails.org/index.php/Archive

Project page on github: https://github.com/remram44/file_archive

### CODE REVIEW

**Comment by remram44** [comment]
Ready!

**Comment by dakoop** [comment]
Tommy, note the dependence on file_archive for the binaries. This is just python code.

**Comment by rexissimus** [comment]
file_archive can be installed through pip. I will test and make sure they are included in the binaries.

**Comment by remram44** [comment]
Needs #1010

**Comment by rexissimus** [comment]
Looks good, I added file_archive to build machines and merged #1010.
The subclassed Modules are missing docstrings, should we add that?

**Comment by remram44** [comment]
dcbd9124 adds docstrings for some `QueryCondition` subclasses, are these what you meant?

**Comment by rexissimus** [comment]
This is a minor issue, but the "*Path" modules have docstrings but corresponding "*File" and "*Dir" modules does not.
The modules are very similar so maybe they could share docstrings.
Would it make sense if vistrails could take module docstrings from superclasses if it was missing?

**Comment by dakoop** [comment]
Yes. There may be some cases where the subclass changes the way things are done, but hopefully the inheritance will prompt developers to make sure the documentation is updated. We should check our own code on this.

**Comment by remram44** [comment]
Indeed I assumed it would get inherited.

I can see arguments for inheriting (like here) and not inheriting (different modules have different behaviors, even if that difference can be minor). It not really any trouble for me to copy the docstring so I'll probably do that.

Python doesn't inherit docstrings either, so it's probably fine to stick to this.

**Pull request merged**
