### PR TITLE
Test for vtl examples

### LINKED ISSUE #1107: Some Users Guide Examples are not working
There seems to be several issues with the linked examples in the users guide (Tested in single instance mode)
- [x] [cfassistant2.vtl](www.vistrails.org/usersguide/v2.2/examples/cfassistant2.vtl) - Unexpected Exception during upgrade
- [x] [global_variables1.vtl](www.vistrails.org/usersguide/v2.2/examples/global_variables_1.vtl) - Error upgrading vtkDataSetReader (same for [vtk_http.vtl](www.vistrails.org/usersguide/v2.2/examples/vtk_http.vtl))
- [x] [mashups1.vtl](www.vistrails.org/usersguide/v2.2/examples/mashups1.vtl) - Error: `Cannot translate old mashup through upgrade`
- [x] [pe1.vtl](www.vistrails.org/usersguide/v2.2/examples/pe1.vtl) - Parameter Exploration is missing parameters (same for pe2, pe3, pe4)

### PR DESCRIPTION
**Pull request by rexissimus**
Fixes #1107

### CODE REVIEW

**Comment by remram44** [comment]
[lion-conda-master](http://216.165.113.90:9050/builders/lion-conda-master/builds/82) failed, but it seems to pass everywhere else

**Comment by remram44** [comment]
Works now that suds is installed!

**Comment by remram44** [comment]
:broken_heart: Tests didn't pass on [debian6-64-v2.2](http://vistrails.poly.edu:9050/builders/debian6-64-v2.2/builds/71/steps/TestSuite/logs/stdio), [lion-v2.2](http://vistrails.poly.edu:9050/builders/lion-v2.2/builds/70/steps/TestSuite/logs/stdio), [win7-32-v2.2](http://vistrails.poly.edu:9050/builders/win7-32-v2.2/builds/70/steps/TestSuite/logs/stdio)

**Comment by rexissimus** [comment]
It looks like commit a65bc935c7984c0a044a0b86002d479ef93ccd0c is causing the test in `core/db/locator.py` to fail. Is there a bug there or should I be validating the pipeline in some different way?

**Comment by rexissimus** [comment]
48417312996026a98f7cbe4f4a4468923925c28e adds a missing validate call so that the pipeline gets correctly marked as valid. Does this look correct?

**Comment by remram44** [comment]
Hmm, yes. There are still too many branches in this thing...

**Pull request merged**
