### PR TITLE
New api, to easily use VisTrails in other applications

### PR DESCRIPTION
**Pull request by remram44**
This adds an easy-to-use API, that hides the internals and exposes wrappers.

* [X] VisTrails initialization
 * Don't load packages at startup
 * Fixes argv handling for IPython
 * Fixes logging
* [X] Loading pipelines and vistrails
* [X] Package and namespace wrapper
* [X] Execution
 * Sending custom input to pipeline
   * [X] Setting constants as input
    * [ ] Sending "live" objects as input
 * [X] Getting execution output
 * [X] IPython integration (rich-text)
* "Output modes"
 * [X] `MplFigureOutput` module
 * [x] `RichTextOutput` module? (see #1009)
 * [x] `TableOutput` module
 * [x] `vtkRendererOutput` module
* ~~Pipeline modification~~, can be done in a future iteration

Current status: [notebook](http://nbviewer.ipython.org/github/VisTrails/VisTrails/blob/new-api-test/vtapitest.ipynb)

### CODE REVIEW

**Comment by remram44** [comment]
IPython integration is there! Pipelines are rendered with Graphviz:

[](http://nbviewer.ipython.org/github/VisTrails/VisTrails/blob/53cba6b14637cdd87bf162b8e592d8b7c8c1e7d7/vtapitest.ipynb)

as well as version trees. Some `PathObject`s, like images, also show up as rich objects:

[](http://nbviewer.ipython.org/github/VisTrails/VisTrails/blob/53cba6b14637cdd87bf162b8e592d8b7c8c1e7d7/vtapitest.ipynb)

**Comment by tacaswell** [comment]
Well, that is cool.

**Comment by tacaswell** [comment]
attn @danielballan

**Comment by vistrails-dev** [comment]
Way cool!

On Tue, Feb 17, 2015 at 6:25 PM, Remi Rampin <notifications@github.com>
wrote:

> IPython integration is there! Pipelines are rendered with Graphviz:
>
>
> <http://nbviewer.ipython.org/github/VisTrails/VisTrails/blob/53cba6b14637cdd87bf162b8e592d8b7c8c1e7d7/vtapitest.ipynb>
>
> as well as version trees. Some PathObjects, like images, also show up as
> rich objects:
>
>
> <http://nbviewer.ipython.org/github/VisTrails/VisTrails/blob/53cba6b14637cdd87bf162b8e592d8b7c8c1e7d7/vtapitest.ipynb>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/VisTrails/VisTrails/pull/24#issuecomment-74777882>.
>
> _______________________________________________
> vistrails-dev mailing list
> vistrails-dev@vistrails.org
> http://lists.vistrails.org/mailman/listinfo/vistrails-dev
>
>


-- 
Juliana Freire, PhD
Professor, Computer Science & Engineering
Director of Graduate Studies, Center for Data Science (CDS)
Faculty Member, Center for Urban Science & Progress (CUSP)
New York University
juliana.freire@nyu.edu
(718) 260-4128

Admin: Ann Messinger, Program Operations Manager
      phone: (718) 260-4057, email: am6179@nyu.edu

**Comment by remram44** [comment]
After today's meeting: could add a way to define modules with a cell magic, and add them or replace them in the workflow.
```
%%pythonsource my_adder
#in: value1 basic:Integer
#in: value2 basic:Integer
#out: value basic:Integer
value = value1
value += value2
```
```
vistrail.replace_module('+', my_adder)
```

**Comment by remram44** [comment]
Something that I'm missing is overriding output modules configuration. What I had initially envisioned was:
```python
import vistrails as vt
vistrail = vt.load_vistrail("terminator.vt")

with vt.output_mode('ImageOutput', 'file',
                    directory='/tmp/', prefix='apitest_image', format='png'):
    vistrail.execute()
```

**Pull request merged**
