### PR TITLE
update_copyright_year.py & remove trailing whitespace in copyright blocks

### PR DESCRIPTION
**Pull request by remram44**
I might have gone overboard with that, maybe only fix whitespace in Python code.

### CODE REVIEW

**Comment by rexissimus** [comment]
It should be fine. But the script only works on .py files for safety. We should run it for other file and update other files like splash.svg and possibly others.

**Comment by remram44** [comment]
I do not know whether this should be "2011-2015 NYU-Poly" or "2011-2014 NYU-Poly, 2014-2015 New York University" or even "2011-2015 New York University".

**Comment by rexissimus** [comment]
Yes, we should discuss this. Also, the text still mentions "University of Utah".

**Comment by remram44** [comment]
Copyright headers now look like this:
```python
## Copyright (C) 2014-2015, New York University.
## Copyright (C) 2011-2014, NYU-Poly.
## Copyright (C) 2006-2011, University of Utah.
## All rights reserved.
## Contact: contact@vistrails.org
```

**Comment by rexissimus** [comment]
I updated other file types as well and removed "University of Utah" from the copyright text. Also updated the splash and the mac dmg binary. I think that should be everything. Different file types with different formatting and different types of generators makes updating a pain :(

**Pull request merged**
