### PR TITLE
Job tests

### PR DESCRIPTION
**Pull request by rexissimus**
This adds the following tests:
    * Run a job (suspend+finish)
    * Run job in Group
    * Run jobs in list loop
    * Run jobs in Map
    * Run Parameter Exploration with Job (suspend+finish)
    * Run Mashup with Job (suspend+finish)

Also fixes some related issues:
* Fixed QNumericStepper.contentsChanged parameters
* Made mashup app notifications non-blocking
* Add custom name to parent jobs
* Fixed jobs in Groups by allowing parent jobs to have no handle

### CODE REVIEW

**Comment by remram44** [comment]
This `myjob.py` can't stay under `vistrails/packages/`

**Comment by rexissimus** [comment]
I was planning to use it an example, similarly to how PythonCalc is used. I don't know if we have a better place to put example packages that are not really useful?

**Comment by remram44** [comment]
Test packages are usually under `vistrails/tests/resources/` (cf bcdf0dee), but I agree that in this case it also qualifies as an example of how to use jobs. But perhaps it could just be in the [internal docs](../pull/1116)?

**Comment by rexissimus** [comment]
This is for the package developer documentation since jobs need to be implemented in modules. This could be referenced by the internal docs, but I think that documentation should go deeper and describe the job system at a lower level.

**Pull request merged**
