### PR TITLE
Qt5 fixes

### PR DESCRIPTION
**Pull request by rexissimus**
We should support Qt 5 and ship it in the binaries (if there are no backwards compatibility issues). The main reason is to support the new WebKit. This will need a recompile of everything using Qt.

This is now working. Just needs some more testing.

* [X] Vistrails runs
* [X] Test with VTK
* [ ] Use WebEngine?
* [ ] More testing needed
* [ ] Update Mac build
* [ ] Update Windows build

### CODE REVIEW

**Comment by remram44** [comment]
As far as I know, VTK links with Qt, but VTK (at least 6+) supports Qt5?

**Comment by rexissimus** [comment]
Yes, I need to try compiling VTK against Qt5. But I got stuck on some problem with my installation picking up Qt4 libraries and segfaulting.

**Comment by rexissimus** [comment]
The newly released Qt 5.5 deprecates WebKit in favor of WebEngine. We should probably focus on WebEngine.

**Comment by rexissimus** [comment]
[The Bokeh package](https://github.com/VisTrails/VisTrails/tree/python-wrapper-bokeh) would benefit from QWebEngine in Qt5. But it does not look like WebEngine works with PyQt4 (yet). We could port vistrails to PyQt5 without too much effort (with the help of scripts like [pyqt4topyqt5](https://github.com/rferrazz/pyqt4topyqt5)). But that would break compatibility with existing PyQ4 code, and a compatibility layer would probably be too complicated to be useful.

**Comment by remram44** [comment]
Decision is to develop on #1143 directly.

**Pull request closed without merging**
