### PR TITLE
Tensorflow package

### PR DESCRIPTION
**Pull request by remram44**
The design is a bit weird here because of the Variable operations, which are used to provide feedback between executions of the graph.

### CODE REVIEW

**Comment by remram44** [comment]
Mandelbrot example

**Comment by remram44** [comment]
Alright, I got the MNIST example working. However the way data is fed into the graph is awkward ATM: I create a Python generator from a PythonSource, that yields dicts, and this is given to the run module. However I don't have a better option until better streaming support appears (and even then, there'll be dicts).

**Comment by remram44** [comment]
MNIST example

**Comment by julianafreire** [comment]
@remram44  Should we announce this package now? Or would you rather wait to have streams working before?

**Comment by remram44** [comment]
The streaming rework would make feeding data to a TensorFlow pipeline less awkward, but doesn't improve anything else. The package can be released in the next version of VisTrails.

I'm looking into porting this on the new wrapping code from Tommy @rexissimus.

**Pull request merged**
